### ISSUE TITLE
how to know when the device is connected to the app successfully

### ISSUE THREAD

**Issue by dinhchinh82** [linkwil/WeHomeSDK#7]
Hello,

We are trying to integrate your camera to our own application. 
According to the SDK, the wifi setting is based on the sound. 
Could you help me how to know when the wifi setting is completed successfully?

Your application on App store works well but your demo app did not work. We tested on iOS platform.

Thank you.

**Comment by xiaojinsheng** [comment]
You can try to connecting to the camera with a timeout value, if connected, it means completed successfully, otherwise, wifi setting is on progress or timeout

**Comment by dinhchinh82** [comment]
Thank you
