### ISSUE TITLE
How to know the event when the camera close the connection

### ISSUE THREAD

**Issue by dinhchinh82** [linkwil/WeHomeSDK#9]
Hello,

Could you tell me how to detect the event when the camera closes the connection? 

We checked your SDK but it seems there is no appropriate event.

It will be used to notify user when the connection is disconnected. 

Thank you.

**Comment by xiaojinsheng** [comment]
The sdk didn't support that function yet, we suggest you add a countdown timer on the viewing screen.

**Comment by dinhchinh82** [comment]
We got it. Thank you.
